### ISSUE TITLE
problem with slightly larger post data

### ISSUE THREAD

**Issue by alanbradleyleroy** [sworteu/Express#2]
Hello,

I seem to have a problem using post data larger than 700K(image files).  When I look at the request.datavailable method it reads in all the data using read(thus clearing the buffer).  However if the contentReceivedLength<ContentLength then exits.

Seems to me that the read data is lost?  It is not read with lookahead  or cached somewhere for combining with future data coming in?  Aloa Express used lookahead to get the contentReceivedLength before actually reading in the data received.

Maybe I am misunderstanding the issue?  I have set maxentitysize to 30MB so this is not the problem.  The server never completes the transfer and only a HTTPStatus erorr of 0 is eventually returned.

Thanks,

Alan

**Comment by sworteu** [comment]
Hi @alanbradleyleroy did you try to debug the project to see where you have the data (or part thereof) ?

**Comment by alanbradleyleroy** [comment]
Hello,

I fixed the problem I was having by changing the following code in the
DataAvailable event of the Express Request

// If we haven't received all of the content...
If contentReceivedLength < ContentLength Then
  // Continue receiving data...
  Return
End If

to


// If we haven't received all of the content...
If ContentReceivedLength < ContentLength Then
  // Continue receiving data...
  Return
else
  Data=ReadAll(Encodings.UTF8)
  Data = Data.DefineEncoding(Encodings.UTF8)// get all data
End If

I have not hit a limit with much larger data size.  Hope this helps you.

Alan

**Comment by sworteu** [comment]
Hi Alan thanks. We do notice you force an encoding without checking the headers in advance (the request could have binary data instead). we will review this code and see if we can find a solution for all requests. Thanks for your information!
