### ISSUE TITLE
DemoMultipartForms Doesn't Work

### ISSUE THREAD

**Issue by gkjpettet** [sworteu/Express#7]
I'm not sure if I'm doing something wrong but I don't think the multipart form demo is working at all.

if I uncomment the multipart demo in `App.RequestHandler` to enable the demo and visit `localhost:8080` I get the form to upload files. No matter what I try to upload the request eventually times out and as far as I can see the `DemoMultipartForms.RequestProcess` method isn't being called.

Can you check if this demo works for you? I'm on macOS.

**Comment by gkjpettet** [comment]
Also, it seems that even as I type the address for local host into Chrome or Safari, the `RequestProcess` method gets called before I can even see the returned HTML in the browser. It's almost like the browser is trying to be smart and grab the resources before I finish typing. Not sure if this has something to do with it. Certainly I am unable to catch anything with a breakpoint in `DemoMultipartForms.RequestProcess` after I click the submit button in the browser.

**Comment by sworteu** [comment]
It seems the body remains empty which is rather odd. I maybe looking into this later if i have some time.
In the meantime if you find anything, please report it.

**Comment by sworteu** [comment]
I have found that the body was separated by CRLF + CRLF, by changing that to a local buffer we now get full content (all chunks) but it still doesn't close (respond) properly and doesn't save the file. A new branche will be created to fix this issue.

**Comment by jo-tools** [comment]
The issue had been in `Express.Request`.

- DataAvailable: uses Lookahead.Bytes to determine if the Content has been fully received
- Fix in Method BodyGet, so that Multipart Form Content is no longer stripped
- DataGet and BodyGet in now called in Method "Process"

I have fixed this along the way when creating Pull Request #10 *(Express 6.1.0 | EventLog | Demo GUI)*.

**Comment by jo-tools** [comment]
@gkjpettet I think you can close this issue as this is fixed in Express 6.1.0.
And maybe you'd like to create a Tag and/or Release in this Repo.

**Comment by gkjpettet** [comment]
Closed as fixed in 6.1.0: https://github.com/sworteu/Express/releases/tag/V6.1.0
